Repository cosmos/ibc-rs, pull requests merged in 2023-12, with the labels that each got.

#1005 feat: introduce convenience Status::verify_is_active method
  .changelog/unreleased/improvements/1005-status-verify-active.md
  ibc-core/ics02-client/src/handler/update_client.rs
  ibc-core/ics02-client/src/handler/upgrade_client.rs
  ibc-core/ics02-client/types/src/status.rs
  ibc-core/ics03-connection/src/handler/conn_open_ack.rs
  ibc-core/ics03-connection/src/handler/conn_open_confirm.rs
  ibc-core/ics03-connection/src/handler/conn_open_init.rs
  ibc-core/ics03-connection/src/handler/conn_open_try.rs
  ibc-core/ics04-channel/src/handler/acknowledgement.rs
  ibc-core/ics04-channel/src/handler/chan_close_confirm.rs
  ibc-core/ics04-channel/src/handler/chan_close_init.rs
  ibc-core/ics04-channel/src/handler/chan_open_ack.rs
  ibc-core/ics04-channel/src/handler/chan_open_confirm.rs
  ibc-core/ics04-channel/src/handler/chan_open_init.rs
  ibc-core/ics04-channel/src/handler/chan_open_try.rs
  ibc-core/ics04-channel/src/handler/recv_packet.rs
  ibc-core/ics04-channel/src/handler/send_packet.rs
  ibc-core/ics04-channel/src/handler/timeout.rs
  ibc-core/ics04-channel/src/handler/timeout_on_close.rs
Labels: O: maintainability

#1004 fix: packet sequence in Timeout handlers should be encoded in big-endian
  .changelog/unreleased/bug-fixes/1004-fix-packet-sequence-encoding.md
  ibc-core/ics24-host/types/src/identifiers/sequence.rs
Labels: A: bug

#1012 feat: establish ICS-721 boilerplate, ready for new additions
  Cargo.toml
  ibc-apps/Cargo.toml
  ibc-apps/README.md
  ibc-apps/ics721-nft-transfer/Cargo.toml
  ibc-apps/ics721-nft-transfer/src/context.rs
  ibc-apps/ics721-nft-transfer/src/handler/mod.rs
  ibc-apps/ics721-nft-transfer/src/lib.rs
  ibc-apps/ics721-nft-transfer/src/module.rs
  ibc-apps/ics721-nft-transfer/types/Cargo.toml
  ibc-apps/ics721-nft-transfer/types/src/error.rs
  ibc-apps/ics721-nft-transfer/types/src/events.rs
  ibc-apps/ics721-nft-transfer/types/src/lib.rs
  ibc-apps/ics721-nft-transfer/types/src/msgs/mod.rs
  ibc-apps/src/lib.rs
Labels: O: new-feature
