Repository cosmos/ibc-rs, pull requests merged in 2023-11, with the labels that each got.

#939 perf: avoid temporary Vec allocations when computing commitments
  .changelog/unreleased/improvements/939-less-alloc.md
  crates/ibc/src/core/ics04_channel/commitment.rs
Labels: O: performance

#949 deps: bump `ibc-proto-rs` to v0.38.0 + some other dependency upgrades
  .changelog/unreleased/breaking-changes/949-bump-ibc-proto-rs-to-v0380.md
  ci/cw-check/Cargo.lock
  ci/no-std-check/Cargo.lock
  ci/no-std-check/Cargo.toml
  crates/ibc-derive/src/consensus_state.rs
  crates/ibc-query/Cargo.toml
  crates/ibc/Cargo.toml
  crates/ibc/src/applications/transfer/error.rs
  crates/ibc/src/applications/transfer/msgs/transfer.rs
  crates/ibc/src/clients/ics07_tendermint/client_state.rs
  crates/ibc/src/clients/ics07_tendermint/consensus_state.rs
  crates/ibc/src/clients/ics07_tendermint/header.rs
  crates/ibc/src/clients/ics07_tendermint/misbehaviour.rs
  crates/ibc/src/clients/ics07_tendermint/trust_threshold.rs
  crates/ibc/src/core/context.rs
  crates/ibc/src/core/ics02_client/consensus_state.rs
  crates/ibc/src/core/ics02_client/error.rs
  crates/ibc/src/core/ics02_client/height.rs
  crates/ibc/src/core/ics02_client/msgs/create_client.rs
  crates/ibc/src/core/ics02_client/msgs/misbehaviour.rs
  crates/ibc/src/core/ics02_client/msgs/update_client.rs
  crates/ibc/src/core/ics02_client/msgs/upgrade_client.rs
  crates/ibc/src/core/ics03_connection/connection.rs
  crates/ibc/src/core/ics03_connection/error.rs
  crates/ibc/src/core/ics03_connection/handler/conn_open_ack.rs
  crates/ibc/src/core/ics03_connection/handler/conn_open_confirm.rs
  crates/ibc/src/core/ics03_connection/handler/conn_open_try.rs
  crates/ibc/src/core/ics03_connection/msgs/conn_open_ack.rs
  crates/ibc/src/core/ics03_connection/msgs/conn_open_confirm.rs
  crates/ibc/src/core/ics03_connection/msgs/conn_open_init.rs
  crates/ibc/src/core/ics03_connection/msgs/conn_open_try.rs
  crates/ibc/src/core/ics03_connection/version.rs
  crates/ibc/src/core/ics04_channel/channel.rs
  crates/ibc/src/core/ics04_channel/handler/chan_close_confirm.rs
  crates/ibc/src/core/ics04_channel/handler/chan_open_ack.rs
  crates/ibc/src/core/ics04_channel/handler/chan_open_confirm.rs
  crates/ibc/src/core/ics04_channel/handler/chan_open_try.rs
  crates/ibc/src/core/ics04_channel/handler/timeout_on_close.rs
  crates/ibc/src/core/ics04_channel/msgs/acknowledgement.rs
  crates/ibc/src/core/ics04_channel/msgs/chan_close_confirm.rs
  crates/ibc/src/core/ics04_channel/msgs/chan_close_init.rs
  crates/ibc/src/core/ics04_channel/msgs/chan_open_ack.rs
  crates/ibc/src/core/ics04_channel/msgs/chan_open_confirm.rs
  crates/ibc/src/core/ics04_channel/msgs/chan_open_init.rs
  crates/ibc/src/core/ics04_channel/msgs/chan_open_try.rs
  crates/ibc/src/core/ics04_channel/msgs/recv_packet.rs
  crates/ibc/src/core/ics04_channel/msgs/timeout.rs
  crates/ibc/src/core/ics04_channel/msgs/timeout_on_close.rs
  crates/ibc/src/core/msgs.rs
  crates/ibc/src/hosts/tendermint/upgrade_proposal/plan.rs
  crates/ibc/src/hosts/tendermint/upgrade_proposal/proposal.rs
  crates/ibc/src/lib.rs
  crates/ibc/src/mock/client_state.rs
  crates/ibc/src/mock/consensus_state.rs
  crates/ibc/src/mock/context.rs
  crates/ibc/src/mock/header.rs
  crates/ibc/src/mock/host.rs
  crates/ibc/src/mock/misbehaviour.rs
Labels: dependencies

#966 docs: ADR-008 to restructure the `ibc` crate
  docs/architecture/adr-008-restructure-ibc-crate.md
Labels: S: docs

#970 optimization: reduce heap allocation
  .changelog/unreleased/improvements/970-reduce-heap-allocation.md
  ibc-core/ics02-client/types/src/events.rs
  ibc-core/ics04-channel/types/src/events/packet_attributes.rs
  ibc-primitives/src/prelude.rs
Labels: O: optimization
